### ISSUE TITLE
AWS/Azure/GCP Credentials 

### ISSUE THREAD

**Issue by najafmurtaza** [pulumi/automation-api-examples#14]
Is there a ways to pass cloud credentials using code(Automation API) specifically golang?

**Comment by lukehoban** [comment]
Yes - you can call [`SetConfig`](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#LocalWorkspace.SetConfig) to set any cloud configuation you need - such as [`aws:accessKey`](https://www.pulumi.com/docs/intro/cloud-providers/aws/#configuration).
