### ISSUE TITLE
1. Roll back option, 2. convert Output<T> to T, 3. wait then resume, 4. Remove randomness

### ISSUE THREAD

**Issue by najafmurtaza** [pulumi/automation-api-examples#23]
Four questions

1. Is there auto-roll back option in pulumi? if xyz resource isn't found or created can we auto roll back all resources in stack?

2. can we convert pulimi.IDOutput to string and *string?

3. I am creating EC2 machine and right after that I am running ansible. But the problem is machine state gets to “running” after some time and due to that ansible fails to reach the server. Is there await or anything in native pulumi as an option while creating EC2?
I know we can add our own custom loop and check state of the machine and then continue but I want to try pulumi option if available. 

4. I noticed pulumi randomly starts executing code in deployfunc of automation api. Is there a way I can remove it and make it to execute code from top to bottom? 
I know about dependson option, but it executes print statements before resource creation as well which I want to avoid and execute the code from top to bottom.

P.S: I am using Golang.

**Comment by EvanBoyle** [comment]
Hi @najafmurtaza!

This repo is for examples for the automation API. For general purpose questions about pulumi, I recommend our community slack as a good place to start: https://slack.pulumi.com/

To answer your questions:

1. There is not currently an auto-rollback feature. There's an issue here you can comment/follow along on: https://github.com/pulumi/pulumi/issues/96
2. TLDR; is that the raw values backing inputs/outputs can only be accessed within `ApplyT` methods. Please read the docs on input/output for a full explanation of the programming model https://www.pulumi.com/docs/intro/concepts/inputs-outputs/
3. I would recommend running ansible as a separate step within your deployment. Wrapping your deployment with automation API is a good way to achieve this. There is an issue tracking adding native support for this in pulumi: https://github.com/pulumi/pulumi/issues/1691
4. There is no way to force synchronous resource creation at the moment. `Apply` callbacks are kind of like promises. They run as soon as the underlying resource is available. Some resources may become available before others. I'd recommend reading more of the architectural and programming model materials here: https://www.pulumi.com/docs/intro/concepts/
