### ISSUE TITLE
Example with remote state

### ISSUE THREAD

**Issue by yannh** [pulumi/automation-api-examples#3]
Hello! I think all examples use a local state file... I I'm not sure, are remote state backends supported at all? It would be super useful to have an example :bow:   Thanks a lot, the automation API seems super interesting :rocket:

**Comment by stack72** [comment]
Hi @yannh 

So all of the examples work based on where you have already been logged into with Pulumi

If you want to use an alternative backend, then *before* running your automation program, use "Pulumi login <my backend>"

The automation api itself doesn't support a login operation at this point but it's something that may get added as more people request it

I hope this helps?

Paul

**Comment by yannh** [comment]
I understand, that was not clear to me, thanks!

**Comment by stack72** [comment]
Sorry that wasn't clear @yannh - let us know if this isn't working well for you and we can look into it
