### ISSUE TITLE
stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables

### ISSUE THREAD

**Issue by najafmurtaza** [pulumi/automation-api-examples#4]
Getting this error in inline S3 bucket program

`stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables`

**Comment by EvanBoyle** [comment]
@najafmurtaza It sounds like you are using a self-managed backend and/or a custom encryption scheme. Is that accurate? 

If so you'll need to persist the `StackSettings` object after the stack is created and supply that same `StackSettings` when selecting the stack in the future. 

If you are working locally, you can do this by specifying the `workDir` option to `.`.

**Comment by najafmurtaza** [comment]
I am working locally.

I am using the same code provided in this repo inline example.
Can you tell where to pass workDir in golang?

**Comment by EvanBoyle** [comment]
Check out `LocalWorkspaceOption`: 

https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#example-UpsertStackInlineSource
https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#LocalWorkspaceOption
https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#WorkDir

```go
s, err := auto.UpsertStackInlineSource(ctx, stackName, projectName, deployFunc, WorkDir(filepath.Join("."))
```

**Comment by najafmurtaza** [comment]
Still getting the same error.
`	s, err := auto.UpsertStackInlineSource(ctx, stackName, projectName, deployFunc, auto.WorkDir(filepath.Join(".")))
`

Error:
`Failed to refresh stack: code: 255
, stdout: 
, stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
`

**Comment by EvanBoyle** [comment]
I imagine you have already created this stack? In that case, you have lost the encryption material that gets stored in stack settings. You will need to create a fresh stack (different stack name, or remove the existing stack).

**Comment by najafmurtaza** [comment]
There is this main.go in current directory.
https://github.com/pulumi/automation-api-examples/blob/main/go/inline_program/main.go

To avoid confusion, I am running this same  file with `go run main.go` as shown on Pulumi Youtube but still getting the same error.

**Comment by EvanBoyle** [comment]
The `pulumi.yaml` and `pulumi.stack.yaml` files will get created in the current working directory when you run the program and create the stack for the first time. They will not be created when selecting the stack. When you select the stack it is expected that those files exist in the working directory, or that you specify them via `ProjectSettings` and `StackSettings`.

Since you don't have them, I would suggest creating a new stack by changing the name of the stack on this line: https://github.com/pulumi/automation-api-examples/blob/main/go/inline_program/main.go#L88

**Comment by najafmurtaza** [comment]
It does create the files but still getting the same error even with totally new stack name. 

Here is what I did
1. Removed all files except main.go
2. Changed stack name
3. Run again but got the same error.

**Comment by EvanBoyle** [comment]
Can you share your `pulumi.stack.yaml` and `pulumi.yaml` that gets created?

**Comment by najafmurtaza** [comment]
pulumi.stack.yaml
```
config: 
aws:region: us-east-1
```

pulumi.yaml
```
name: inline_EC2  
runtime: go
```

**Comment by EvanBoyle** [comment]
Have you tried setting the environment variable in the error message?

**Comment by EvanBoyle** [comment]
If you are using the passphrase secrets provider, you'll need to specify it either as an environment variable when running the process, or via workspace environment variables. 

https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#EnvVars

**Comment by najafmurtaza** [comment]
1. How can I stop passphrase usage?
2. And how to pass it through code?

**Comment by EvanBoyle** [comment]
Documentation on secrets providers here would be worth reading: https://www.pulumi.com/docs/intro/concepts/config/#configuring-secrets-encryption

Your stack has to have a secrets provider. If you want to use a different one, you can modify the example to specify a secrets provider at the workspace level: 

https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#example-LocalWorkspace-SecretsProvider

That example shows two things:

1. Specifying a custom secrets provider
2. Specifying environment variables that will be passed to all pulumi commands (the answer to your question 2, how to pass through code).

**Comment by EvanBoyle** [comment]
Note that when working locally, you need to manage some of this yourself.

You can avoid having to set these options if you log in via the pulumi console and use that as your backend.

**Comment by najafmurtaza** [comment]
Thanks @EvanBoyle it worked. I was thinking to NOT use secrets, but using is a must.

**Comment by gbegher** [comment]
Maybe a clearification about something where the code sample @EvanBoyle provided might be misleading:

* If you're using a `secretsProvider` such as `awskms`, setting the `PULUMI_CONFIG_PASSPHRASE_FILE` variable is NOT required

It is enough to set `LocalWorspaceOptions` such as

```(typescript)
// code is in typescript
const backendUrl = "s3://..."
const secretsProvider = "awskms:///..." // notice that it's `///` not `//`

const localWorkspaceOptions = {
  projectSettings: {
    name: projectName,
    runtime: "nodejs",
    backend: { url: backendUrl },
  },
  secretsProvider,
  stackSettings: {
    [stackName]: {
      secretsProvider,
      config: {
        "aws:region": "some-aws-region",
      },
    },
  },
}
```

If the error about `PULUMI_CONFIG_PASSPHRASE_FILE` occurs with code such as this, I think this might have the following reason:

In the situation where a previous state of a stack with the same name is:
* stored on the same S3 bucket
* BUT using a different secret

I think in this case, pulumi fails to use the specified secrest provider and defaults to the `PASSPHRASE` provider resulting in this misleading error message.

What fixed it for me, was to delete the previously stored states and history.

Maybe there should be a different error message in this case? @EvanBoyle

**Comment by vmanikes-dd** [comment]
@gbegher Your answer helped me to fix this issue. Thank you

**Comment by ryan-mirman-convex** [comment]
The issues I was having with this was due to [pulumi actions](https://github.com/pulumi/actions) updating the stack config file during the CI pipeline when using the KMS secret provider. Pulumi was adding the keys `secretsprovider` and `encryptedkey` to the stack config file.

The `encryptedkey` value is the state encryption key, encrypted by the secrets provider, without it, pulumi cannot decrypt the existing state. If the stack config file (`Pulumi.<stack>.yaml`) is missing this key, a new encrypted key gets generated and the stack config file gets updated with these values. This change needs to be committed to the repository or else it will keep regenerating this key every CI run.
