### ISSUE TITLE
example python code does not work within latest pulumi lib version

### ISSUE THREAD

**Issue by bernardolsp** [pulumi/automation-api-examples#74]
### What happened?

hey 👋 
first of all - thanks for putting this repo up. im new to pulumi and having all this is pretty good!

while trying to partially-replicate https://github.com/pulumi/automation-api-examples/blob/main/python/inline_secrets_provider/main.py#L70, I noticed that at least this https://github.com/pulumi/automation-api-examples/blob/main/python/inline_secrets_provider/main.py#L66-L70 does not work anymore.

### Example

Try to run:
```python
project_settings=auto.ProjectSettings(
    name=project_name,
    runtime="python",
    backend={"url": "file://~/.pulumi-local"})
```
You will see an error like:
`AttributeError: 'dict' object has no attribute 'to_dict'`

To fix, use:
```
project_settings=auto.ProjectSettings(
    name=project_name,
    runtime="python",
    backend=auto.ProjectBackend(url="file://~/.pulumi-local")
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue @bernardolsp, and sorry for the trouble.
